// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvGEhNOllt8fGmaBa8h5mmNKlzMtahtgg',
    appId: '1:100886085751:android:90514ec922353e83bf8672',
    messagingSenderId: '100886085751',
    projectId: 'mbk-mall',
    databaseURL: 'https://mbk-mall-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mbk-mall.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_VX5nVKUOndHV-VLs92VWPrnRyA3QByI',
    appId: '1:100886085751:ios:9c6b7bd6c0ad301cbf8672',
    messagingSenderId: '100886085751',
    projectId: 'mbk-mall',
    databaseURL: 'https://mbk-mall-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mbk-mall.firebasestorage.app',
    iosClientId: '100886085751-064d5n59hijn3pcv741f8e3prhf75dum.apps.googleusercontent.com',
    iosBundleId: 'com.mbkmall.app',
  );
}
